# Generated by Django 4.0.5 on 2022-06-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_archivo_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT'), #se modifica verbose a RUT
        ),
        migrations.AlterField(
            model_name='producto',
            name='dv',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DV'), #se agrega a la lista
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombres'), #se modifica verbose a Nombres
        ),
        migrations.AlterField(
            model_name='producto',
            name='primer_apellido',
            field=models.CharField(max_length=30, verbose_name='Primer Apellido'), #se agrega a la lista
        ),
        migrations.AlterField(
            model_name='producto',
            name='segundo_apellido',
            field=models.CharField(max_length=30, verbose_name='Segundo Apellido'), #se agrega a la lista
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50, verbose_name='Nombre categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
    ]
